const allMenuItems = [
    { id: 1, name: "Triple Chocolate Square Cake", price: 250, img: "assets/images/Triple Chocolate Square Cake.jpg" },
    { id: 2, name: "Classic Mocha Square Cake", price: 250, img: "assets/images/Classic Mocha Square Cake.jpg" },
    { id: 3, name: "Mango Buttercream Square Cake", price: 250, img: "assets/images/Mango Buttercream Square Cake.jpg" },
    { id: 4, name: "Chocolate Mousse Cake", price: 250, img: "assets/images/Chocolate Mousse Cake.jpg" },
    { id: 5, name: "Sans Rival Square Cake", price: 80, img: "assets/images/Sans Rival Square Cake.jpg" },
    { id: 6, name: "Mango Supreme Cake", price: 50, img: "assets/images/Mango Supreme Cake.jpg" },
    { id: 7, name: "Ube Flan Cake", price: 150, img: "assets/images/Ube Flan Cake.jpg" },
    { id: 8, name: "Ube Overload Cake", price: 150, img: "assets/images/Ube Overload.jpg" },
    { id: 9, name: "Choco Mocha Crunch Cake", price: 150, img: "assets/images/Choco Mocha Crunch Cake.jpg" },
    { id: 10, name: "Ultimate Ube Cake", price: 150, img: "assets/images/Ultimate Ube Cake.jpg" },
    { id: 11, name: "Belgian Chocolate Cake", price: 150, img: "assets/images/Belgian Chocolate Cake.jpg" },
    { id: 12, name: "Pistachio Crunch", price: 250, img: "assets/images/Pistachio Crunch.jpg" },
    { id: 13, name: "Sea Salt Tiramigoo", price: 250, img: "assets/images/Sea Salt Tiramigoo.jpg" },
    { id: 14, name: "Tiramisu", price: 80, img: "assets/images/Tiramisu.jpg" },
    { id: 15, name: "Mango Delight Cake", price: 50, img: "assets/images/Mango Delight Cake.jpg" },
    { id: 16, name: "Mangolicious", price: 150, img: "assets/images/Mangolicious.jpg" },
    { id: 17, name: "Ube Custard", price: 150, img: "assets/images/Ube Custard.jpg" },
    { id: 18, name: "Cookieccino", price: 150, img: "assets/images/Cookieccino.jpg" },
    { id: 19, name: "Burnt Basque Cheesecake", price: 150, img: "assets/images/Burnt Basque Cheesecake.jpg" },
    { id: 20, name: "Crinkle Cheesecake", price: 150, img: "assets/images/Crinkle Cheesecake.jpg" },
    { id: 21, name: "Chocolate Blush", price: 150, img: "assets/images/Chocolate Blush.jpg" },
    { id: 22, name: "Moist Chocolate", price: 150, img: "assets/images/Moist Chocolate.jpg" },
    { id: 23, name: "Black Velvet", price: 150, img: "assets/images/Black Velvet.jpg" },
    { id: 24, name: "Sans Rival", price: 150, img: "assets/images/Sans Rival.jpg" },
    { id: 25, name: "Mango Tart", price: 150, img: "assets/images/Mango Tart.jpg" },
    { id: 26, name: "Classic Caramel", price: 150, img: "assets/images/Classic Caramel.jpg" },
    { id: 27, name: "Mocha Fruitcake", price: 150, img: "assets/images/Mocha Fruitcake.jpg" },
    { id: 28, name: "Choco Overload", price: 150, img: "assets/images/Choco Overload.jpg" },
    { id: 29, name: "Strawberry Floatcake", price: 150, img: "assets/images/Strawberry Floatcake.jpg" },
    { id: 30, name: "BLueberry Cheesecake", price: 150, img: "assets/images/BLueberry Cheesecake.jpg" },
    { id: 31, name: "Almond Choco Sans Rival", price: 150, img: "assets/images/Almond Choco Sans Rival.jpg" },
    { id: 32, name: "Mango Bravo", price: 150, img: "assets/images/Mango Bravo.jpg" },
    { id: 33, name: "Hazelnut Fudge", price: 150, img: "assets/images/Hazelnut Fudge.jpg" },
    { id: 34, name: "Chocolate Layer", price: 150, img: "assets/images/Chocolate Layer.jpg" },
    { id: 35, name: "Caramel Crunchcake", price: 150, img: "assets/images/Caramel Crunchcake.jpg" },
    { id: 36, name: "Strawberry Shortcake", price: 150, img: "assets/images/Strawberry Shortcake.jpg" },
    { id: 37, name: "Mango Fruit Top", price: 150, img: "assets/images/Mango Fruit Top.jpg" },
    { id: 38, name: "Ube Funcake", price: 150, img: "assets/images/Ube Funcake.jpg" }

];    
